// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNFQkS30HwAyn34L76ew5JztouCVP3aqU',
    appId: '1:983401128342:android:de646efb8143f450a07db7',
    messagingSenderId: '983401128342',
    projectId: 'iloveyoutoo-e9e64',
    storageBucket: 'iloveyoutoo-e9e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQwvVYf2lQik5pvrDg3OxN4N5AsE0PXQ',
    appId: '1:983401128342:ios:b1bb5522cc956084a07db7',
    messagingSenderId: '983401128342',
    projectId: 'iloveyoutoo-e9e64',
    storageBucket: 'iloveyoutoo-e9e64.appspot.com',
    androidClientId: '983401128342-14k2rhdhf5fc5fcb8hac1boduc3gvlb4.apps.googleusercontent.com',
    iosClientId: '983401128342-9r6fpisimn9gnhb7rcs8uqgs82ggt3ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.testNotifications',
  );
}
